import React, { useState, useEffect } from 'react';
import {
    ChakraProvider,
    Box,
    VStack,
    Heading,
    Text,
    Divider,
    Input,
    Textarea,
    Button,
    Icon,
    Flex,
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalBody,
    ModalFooter,
    useDisclosure
} from "@chakra-ui/react";
import { FaRobot, FaUser } from 'react-icons/fa';
import { GoogleGenerativeAI } from "@google/generative-ai";

const ChatMessage = ({ role, icon, text }) => (
    <Box style={styles.responseContainer}>
        <Box style={styles.section}>
            <Flex align="center" mb={2}>
                <Icon as={icon} color={role === 'user' ? "teal.500" : "purple.500"} mr={2} />
                <Text style={styles.sectionTitle}>{role === 'user' ? "You asked:" : "AI Chatbot:"}</Text>
            </Flex>
            <Text fontSize="lg">{text}</Text>
        </Box>
    </Box>
);

function AIChatbot() {
    const [question, setQuestion] = useState("");
    const [additionalDetails, setAdditionalDetails] = useState("");
    const [responses, setResponses] = useState([]);
    const [loading, setLoading] = useState(false);
    const [awaitingDetails, setAwaitingDetails] = useState(false);
    const [initialQuestion, setInitialQuestion] = useState("");
    const { isOpen, onOpen, onClose } = useDisclosure(); // Modal control

    // Show the disclaimer modal when the component first loads
    useEffect(() => {
        onOpen();
    }, [onOpen]);

    const handleInitialSubmit = async () => {
        if (!question.trim()) return;
        setLoading(true);

        const newResponses = [...responses, { role: 'user', text: question }];
        setResponses(newResponses);
        setInitialQuestion(question);
        setQuestion("");

        setAwaitingDetails(true);
        setLoading(false);
    };

    const handleDetailsSubmit = async () => {
        if (!additionalDetails.trim()) return;
        setLoading(true);

        const newResponses = [...responses, { role: 'user', text: additionalDetails }];
        setResponses(newResponses);

        try {
            const finalResponse = await generateFinalResponse(initialQuestion, additionalDetails);
            newResponses.push({ role: 'bot', text: finalResponse });
            setResponses(newResponses);
            resetChatState();
        } catch (error) {
            console.error("Error:", error);
            newResponses.push({ role: 'bot', text: "Sorry, I couldn't process your question. Please try again." });
            setResponses(newResponses);
        } finally {
            setLoading(false);
        }
    };

    const generateFinalResponse = async (initialQuestion, additionalDetails) => {
        const genAI = new GoogleGenerativeAI("AIzaSyBjS1JWxIHWelk5RAByztdZ2WzS2X2tlf0"); // Replace with actual API key
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

        const prompt = `
        A user asked: "${initialQuestion}"
        
        Additional details provided: "${additionalDetails}"
        
        Based on the initial question and these additional details, please generate a simple, short, and straightforward response in clear language.
        `;

        const result = await model.generateContent(prompt);
        return result.response.text();
    };

    const resetChatState = () => {
        setAwaitingDetails(false);
        setInitialQuestion("");
        setAdditionalDetails("");
    };

    return (
        <ChakraProvider>
            {/* Disclaimer Modal */}
            <Modal isOpen={isOpen} onClose={onClose} isCentered>
                <ModalOverlay />
                <ModalContent>
                    <ModalHeader>Disclaimer</ModalHeader>
                    <ModalBody>
                        <Text fontSize="sm" color="gray.600">
                            This chatbot is a beta version powered by AI and is intended for informational purposes only. The responses are generated by an AI model and do not constitute medical advice. Please consult a healthcare professional for any medical concerns.
                        </Text>
                    </ModalBody>
                    <ModalFooter>
                        <Button colorScheme="blue" onClick={onClose}>
                            Agree
                        </Button>
                    </ModalFooter>
                </ModalContent>
            </Modal>

            {/* Main Chat Interface */}
            <Box
                bgGradient="linear(to-br, blue.50, gray.50)"
                minHeight="100vh"
                padding={{ base: "1rem", md: "2rem", lg: "3rem" }}
                color="#333"
                display="flex"
                flexDirection="column"
                justifyContent="space-between"
            >
                {/* Header */}
                <VStack
                    spacing={8}
                    align="stretch"
                    width={{ base: "95%", md: "90%", lg: "80%" }}
                    maxWidth="1200px"
                    mx="auto"
                    bg="rgba(255, 255, 255, 0.6)"
                    borderRadius="xl"
                    boxShadow="0px 4px 10px rgba(0, 0, 0, 0.3)"
                    padding={{ base: "1.5rem", md: "2rem", lg: "3rem" }}
                    transition="all 0.3s"
                    _hover={{ boxShadow: "2xl" }}
                    mb={4}
                >
                    <Heading as="h1" size="lg" textAlign="center" color="#00366d">
                        AI Chatbot
                    </Heading>
                    <Text fontSize={{ base: "sm", md: "md" }} textAlign="center" color="#335d8f">
                        How can I help you today? Type your question below.
                    </Text>
                </VStack>

                {/* Chat Display */}
                <VStack
                    spacing={4}
                    align="stretch"
                    width={{ base: "95%", md: "90%", lg: "80%" }}
                    maxWidth="1200px"
                    mx="auto"
                    bg="rgba(255, 255, 255, 0.6)"
                    borderRadius="xl"
                    padding="1.5rem"
                    overflowY="auto"
                    maxHeight="60vh"
                >
                    {responses.map((item, index) => (
                        <ChatMessage
                            key={index}
                            role={item.role}
                            icon={item.role === 'user' ? FaUser : FaRobot}
                            text={item.text}
                        />
                    ))}
                    {loading && <Spinner size="lg" color="blue.500" />}
                </VStack>

                {/* User Input at the Bottom */}
                <Box
                    as="form"
                    width={{ base: "95%", md: "90%", lg: "80%" }}
                    maxWidth="1200px"
                    mx="auto"
                    mt={4}
                    display="flex"
                    justifyContent="center"
                    alignItems="center"
                    padding="1.5rem"
                    bg="rgba(255, 255, 255, 0.8)"
                    borderRadius="md"
                    boxShadow="0px 2px 8px rgba(0, 0, 0, 0.2)"
                >
                    {!awaitingDetails ? (
                        <>
                            <Input
                                placeholder="Type your question here..."
                                value={question}
                                onChange={(e) => setQuestion(e.target.value)}
                                bg="#F9FAFB"
                                borderRadius="md"
                                size="md"
                                width="100%"
                                maxWidth="700px"
                                mr={4}
                                disabled={loading}
                            />
                            <Button
                                bg="#335d8f"
                                color="white"
                                _hover={{ bg: "#0B2545" }}
                                fontSize="md"
                                paddingX="2rem"
                                paddingY="1.5rem"
                                borderRadius="md"
                                onClick={handleInitialSubmit}
                                isLoading={loading}
                            >
                                Submit
                            </Button>
                        </>
                    ) : (
                        <>
                            <Textarea
                                placeholder="Provide additional details here..."
                                value={additionalDetails}
                                onChange={(e) => setAdditionalDetails(e.target.value)}
                                bg="#F9FAFB"
                                borderRadius="md"
                                size="md"
                                width="100%"
                                maxWidth="700px"
                                mr={4}
                                disabled={loading}
                            />
                            <Button
                                bg="#335d8f"
                                color="white"
                                _hover={{ bg: "#0B2545" }}
                                fontSize="md"
                                paddingX="2rem"
                                paddingY="1.5rem"
                                borderRadius="md"
                                onClick={handleDetailsSubmit}
                                isLoading={loading}
                            >
                                Submit
                            </Button>
                        </>
                    )}
                </Box>
            </Box>
        </ChakraProvider>
    );
}

const styles = {
    responseContainer: {
        backgroundColor: '#f9f9fb',
        padding: '1rem',
        borderRadius: '8px',
        boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.1)',
    },
    section: {
        marginBottom: '1rem',
        padding: '1rem',
        backgroundColor: '#ffffff',
        border: '1px solid #e0e0e0',
        borderRadius: '8px',
    },
    sectionTitle: {
        fontSize: '1.25rem',
        fontWeight: 'bold',
        color: '#0b2545',
        marginBottom: '0.5rem',
    },
};

export default AIChatbot;
